package fasolato.click.t9launcher

import android.provider.Settings

object SettingsRepository {
    val entries = listOf(
        SettingsEntry("Impostazioni", Settings.ACTION_SETTINGS),
        SettingsEntry("WiFi", Settings.ACTION_WIFI_SETTINGS),
        SettingsEntry("Bluetooth", Settings.ACTION_BLUETOOTH_SETTINGS),
        SettingsEntry("Rete mobile", Settings.ACTION_NETWORK_OPERATOR_SETTINGS),
        SettingsEntry("Hotspot e tethering", Settings.ACTION_WIRELESS_SETTINGS),
        SettingsEntry("Modalità aereo", Settings.ACTION_AIRPLANE_MODE_SETTINGS),
        SettingsEntry("Utilizzo dati", Settings.ACTION_DATA_ROAMING_SETTINGS),
        SettingsEntry("VPN", Settings.ACTION_VPN_SETTINGS),
        SettingsEntry("NFC", Settings.ACTION_NFC_SETTINGS),
        SettingsEntry("Schermo", Settings.ACTION_DISPLAY_SETTINGS),
        SettingsEntry("Luminosità", Settings.ACTION_DISPLAY_SETTINGS),
        SettingsEntry("Sfondo", Settings.ACTION_DISPLAY_SETTINGS),
        SettingsEntry("Audio", Settings.ACTION_SOUND_SETTINGS),
        SettingsEntry("Suoneria", Settings.ACTION_SOUND_SETTINGS),
        SettingsEntry("Volume", Settings.ACTION_SOUND_SETTINGS),
        SettingsEntry("Notifiche", Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS),
        SettingsEntry("Non disturbare", Settings.ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS),
        SettingsEntry("Batteria", Settings.ACTION_BATTERY_SAVER_SETTINGS),
        SettingsEntry("Risparmio energetico", Settings.ACTION_BATTERY_SAVER_SETTINGS),
        SettingsEntry("Archiviazione", Settings.ACTION_INTERNAL_STORAGE_SETTINGS),
        SettingsEntry("App", Settings.ACTION_APPLICATION_SETTINGS),
        SettingsEntry("App installate", Settings.ACTION_MANAGE_ALL_APPLICATIONS_SETTINGS),
        SettingsEntry("App predefinite", Settings.ACTION_MANAGE_DEFAULT_APPS_SETTINGS),
        SettingsEntry("Posizione", Settings.ACTION_LOCATION_SOURCE_SETTINGS),
        SettingsEntry("GPS", Settings.ACTION_LOCATION_SOURCE_SETTINGS),
        SettingsEntry("Sicurezza", Settings.ACTION_SECURITY_SETTINGS),
        SettingsEntry("Blocco schermo", Settings.ACTION_SECURITY_SETTINGS),
        SettingsEntry("Impronta digitale", Settings.ACTION_SECURITY_SETTINGS),
        SettingsEntry("Privacy", Settings.ACTION_PRIVACY_SETTINGS),
        SettingsEntry("Autorizzazioni app", Settings.ACTION_PRIVACY_SETTINGS),
        SettingsEntry("Account", Settings.ACTION_SYNC_SETTINGS),
        SettingsEntry("Sincronizzazione", Settings.ACTION_SYNC_SETTINGS),
        SettingsEntry("Data e ora", Settings.ACTION_DATE_SETTINGS),
        SettingsEntry("Fuso orario", Settings.ACTION_DATE_SETTINGS),
        SettingsEntry("Lingua", Settings.ACTION_LOCALE_SETTINGS),
        SettingsEntry("Tastiera", Settings.ACTION_INPUT_METHOD_SETTINGS),
        SettingsEntry("Metodo di input", Settings.ACTION_INPUT_METHOD_SETTINGS),
        SettingsEntry("Accessibilità", Settings.ACTION_ACCESSIBILITY_SETTINGS),
        SettingsEntry("Opzioni sviluppatore", Settings.ACTION_APPLICATION_DEVELOPMENT_SETTINGS),
        SettingsEntry("Aggiornamento sistema", Settings.ACTION_SYSTEM_UPDATE_SETTINGS),
        SettingsEntry("Informazioni telefono", Settings.ACTION_DEVICE_INFO_SETTINGS),
        SettingsEntry("Info dispositivo", Settings.ACTION_DEVICE_INFO_SETTINGS),
    )
}
